//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.EntityRuleManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityRulesRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityRulesRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.EntityRuleManagement.EntityRulesRelatedMessages", typeof(EntityRulesRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specification requires the identifier of the entity rule for association..
        /// </summary>
        public static string AddEntityRuleSpecEntityRuleIsEmpty {
            get {
                return ResourceManager.GetString("AddEntityRuleSpecEntityRuleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule specification was added successfuly..
        /// </summary>
        public static string AddEntityRuleSpecSuccessful {
            get {
                return ResourceManager.GetString("AddEntityRuleSpecSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new entity rule specification. Please try again later..
        /// </summary>
        public static string AddEntityRuleSpecUnexpectedError {
            get {
                return ResourceManager.GetString("AddEntityRuleSpecUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule was added successfuly..
        /// </summary>
        public static string AddEntityRuleSuccessful {
            get {
                return ResourceManager.GetString("AddEntityRuleSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new entity rule. Please try again later..
        /// </summary>
        public static string AddEntityRuleUnexpectedError {
            get {
                return ResourceManager.GetString("AddEntityRuleUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity identifier is required to associate the new rule..
        /// </summary>
        public static string AddNewEntityEntityIdEmpty {
            get {
                return ResourceManager.GetString("AddNewEntityEntityIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification for this rule is required..
        /// </summary>
        public static string AddNewEntityNoSpecificationsFound {
            get {
                return ResourceManager.GetString("AddNewEntityNoSpecificationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while associating the destination entity to the entity rule. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string AddNewEntityRuleEntityNotFound {
            get {
                return ResourceManager.GetString("AddNewEntityRuleEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity rule requires a type..
        /// </summary>
        public static string AddNewEntityRuleTypeIsZero {
            get {
                return ResourceManager.GetString("AddNewEntityRuleTypeIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule specification identifier is required to do this operation. If this error persists, please contact support..
        /// </summary>
        public static string DeleteEntityRuleSpecIdIsZero {
            get {
                return ResourceManager.GetString("DeleteEntityRuleSpecIdIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule specification was removed successfuly..
        /// </summary>
        public static string DeleteEntityRuleSpecSuccessful {
            get {
                return ResourceManager.GetString("DeleteEntityRuleSpecSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the entity rule specification. If this error persists, please contact support..
        /// </summary>
        public static string DeleteEntityRuleSpecUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteEntityRuleSpecUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule was removed successfuly..
        /// </summary>
        public static string DeleteEntityRuleSuccessful {
            get {
                return ResourceManager.GetString("DeleteEntityRuleSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the entity rule. If this error persists, please contact support..
        /// </summary>
        public static string DeleteEntityRuleUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteEntityRuleUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the entity cannot be empty..
        /// </summary>
        public static string EntityRuleEntityIdentifierIsEmpty {
            get {
                return ResourceManager.GetString("EntityRuleEntityIdentifierIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the entity rule cannot be empty..
        /// </summary>
        public static string EntityRuleIdentifierIsEmpty {
            get {
                return ResourceManager.GetString("EntityRuleIdentifierIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity rule was found. If this error persists, please contact support..
        /// </summary>
        public static string EntityRuleNotFound {
            get {
                return ResourceManager.GetString("EntityRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rule specification was not found. If this error persists, please contact support..
        /// </summary>
        public static string EntityRuleSpecificationNotFound {
            get {
                return ResourceManager.GetString("EntityRuleSpecificationNotFound", resourceCulture);
            }
        }
    }
}
