//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.Holidays {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HolidayRelatedMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HolidayRelatedMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.Holidays.HolidayRelatedMessages", typeof(HolidayRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the entity holiday. Please try again later..
        /// </summary>
        public static string EntityHolidayCreateError {
            get {
                return ResourceManager.GetString("EntityHolidayCreateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity holiday created successfully..
        /// </summary>
        public static string EntityHolidayCreatedSuccess {
            get {
                return ResourceManager.GetString("EntityHolidayCreatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the entity holiday. Please try again later..
        /// </summary>
        public static string EntityHolidayDeleteError {
            get {
                return ResourceManager.GetString("EntityHolidayDeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity holiday deleted successfully..
        /// </summary>
        public static string EntityHolidayDeletedSuccess {
            get {
                return ResourceManager.GetString("EntityHolidayDeletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid entity holiday data provided..
        /// </summary>
        public static string EntityHolidayInvalidData {
            get {
                return ResourceManager.GetString("EntityHolidayInvalidData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity holiday not found..
        /// </summary>
        public static string EntityHolidayNotFound {
            get {
                return ResourceManager.GetString("EntityHolidayNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the entity holiday. Please try again later..
        /// </summary>
        public static string EntityHolidayUpdateError {
            get {
                return ResourceManager.GetString("EntityHolidayUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity holiday updated successfully..
        /// </summary>
        public static string EntityHolidayUpdatedSuccess {
            get {
                return ResourceManager.GetString("EntityHolidayUpdatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the holiday behaviour. Please try again later..
        /// </summary>
        public static string HolidayBehaviourDeleteError {
            get {
                return ResourceManager.GetString("HolidayBehaviourDeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday behaviour deleted successfully..
        /// </summary>
        public static string HolidayBehaviourDeletedSuccess {
            get {
                return ResourceManager.GetString("HolidayBehaviourDeletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday behaviour data provided..
        /// </summary>
        public static string HolidayBehaviourInvalidData {
            get {
                return ResourceManager.GetString("HolidayBehaviourInvalidData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday behaviour ID provided..
        /// </summary>
        public static string HolidayBehaviourInvalidId {
            get {
                return ResourceManager.GetString("HolidayBehaviourInvalidId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday behaviour not found..
        /// </summary>
        public static string HolidayBehaviourNotFound {
            get {
                return ResourceManager.GetString("HolidayBehaviourNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the holiday behaviour. Please try again later..
        /// </summary>
        public static string HolidayBehaviourUpdateError {
            get {
                return ResourceManager.GetString("HolidayBehaviourUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday behaviour updated successfully..
        /// </summary>
        public static string HolidayBehaviourUpdatedSuccess {
            get {
                return ResourceManager.GetString("HolidayBehaviourUpdatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the holiday catalog. Please try again later..
        /// </summary>
        public static string HolidayCatalogDeleteError {
            get {
                return ResourceManager.GetString("HolidayCatalogDeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday catalog entry deleted successfully..
        /// </summary>
        public static string HolidayCatalogDeletedSuccess {
            get {
                return ResourceManager.GetString("HolidayCatalogDeletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday catalog data provided..
        /// </summary>
        public static string HolidayCatalogInvalidData {
            get {
                return ResourceManager.GetString("HolidayCatalogInvalidData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday catalog ID provided..
        /// </summary>
        public static string HolidayCatalogInvalidId {
            get {
                return ResourceManager.GetString("HolidayCatalogInvalidId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday catalog entry not found..
        /// </summary>
        public static string HolidayCatalogNotFound {
            get {
                return ResourceManager.GetString("HolidayCatalogNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the holiday catalog. Please try again later..
        /// </summary>
        public static string HolidayCatalogUpdateError {
            get {
                return ResourceManager.GetString("HolidayCatalogUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday catalog updated successfully..
        /// </summary>
        public static string HolidayCatalogUpdatedSuccess {
            get {
                return ResourceManager.GetString("HolidayCatalogUpdatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the holiday type. Please try again later..
        /// </summary>
        public static string HolidayTypeDeleteError {
            get {
                return ResourceManager.GetString("HolidayTypeDeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday type deleted successfully..
        /// </summary>
        public static string HolidayTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("HolidayTypeDeletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday type data provided..
        /// </summary>
        public static string HolidayTypeInvalidData {
            get {
                return ResourceManager.GetString("HolidayTypeInvalidData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid holiday type ID provided..
        /// </summary>
        public static string HolidayTypeInvalidId {
            get {
                return ResourceManager.GetString("HolidayTypeInvalidId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday type not found..
        /// </summary>
        public static string HolidayTypeNotFound {
            get {
                return ResourceManager.GetString("HolidayTypeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the holiday type. Please try again later..
        /// </summary>
        public static string HolidayTypeUpdateError {
            get {
                return ResourceManager.GetString("HolidayTypeUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday type updated successfully..
        /// </summary>
        public static string HolidayTypeUpdatedSuccess {
            get {
                return ResourceManager.GetString("HolidayTypeUpdatedSuccess", resourceCulture);
            }
        }
    }
}
