// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSchedularDAL.Data;

#nullable disable

namespace ShiftSchedularDAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240816143954_BaseEntityRules")]
    partial class BaseEntityRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceType", b =>
                {
                    b.Property<int>("AbsenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbsenceTypeId"));

                    b.Property<string>("AbsenceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceTypeId");

                    b.ToTable("AbsenceTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceTypeLocalization", b =>
                {
                    b.Property<int>("AbsenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("AbsenceTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("AbsenceTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.Property<int>("BaseEntityRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaseEntityRuleId"));

                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.HasKey("BaseEntityRuleId");

                    b.HasIndex("RuleTypeId");

                    b.ToTable("BaseEntityRules");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRuleSpecification", b =>
                {
                    b.Property<int>("BaseEntityRuleId")
                        .HasColumnType("int");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<int>("SpecificationValue")
                        .HasColumnType("int");

                    b.HasKey("BaseEntityRuleId", "SpecificationId");

                    b.ToTable("BaseEntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspect", b =>
                {
                    b.Property<int>("BusinessAspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessAspectId"));

                    b.Property<string>("BusinessAspectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessAspectId");

                    b.ToTable("BusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspectLocalization", b =>
                {
                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessAspectDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessAspectId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("BusinessAspectLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.Property<string>("EntityRuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RuleTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityRuleId");

                    b.HasIndex("EntityId");

                    b.HasIndex("RuleTypeId");

                    b.ToTable("EntityRules");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRuleSpecification", b =>
                {
                    b.Property<string>("EntityRuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<string>("AspectReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspectReferenceId2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId2")
                        .HasColumnType("int");

                    b.Property<int>("SpecificationValue")
                        .HasColumnType("int");

                    b.HasKey("EntityRuleId", "SpecificationId");

                    b.ToTable("EntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityTypeId"));

                    b.Property<string>("EntityTypeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("ActiveWorkerStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateSchedules")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.HasKey("EntityId", "WorkerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("WorkerId");

                    b.ToTable("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerAbsence", b =>
                {
                    b.Property<string>("EntityWorkerAbsenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AbsenceApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AbsenceDateDecision")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AbsenceDateDecisionOffset")
                        .HasColumnType("time");

                    b.Property<string>("AbsenceDecisionOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AbsenceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AbsenceStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AbsenceTypeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("DateOffset")
                        .HasColumnType("time");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityWorkerAbsenceId");

                    b.HasIndex("AbsenceTypeId");

                    b.HasIndex("EntityId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerEntityAbsences");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerInvitation", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InviteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillsetIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityId", "Email");

                    b.HasIndex("WorkerId");

                    b.ToTable("EntityWorkerInvitations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("GenderDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("GenderLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationId"));

                    b.Property<string>("LocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleType", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleTypeId"));

                    b.Property<bool>("MultipleSpecification")
                        .HasColumnType("bit");

                    b.Property<string>("RuleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleTypeId");

                    b.ToTable("RuleTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeBusinessAspect", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.HasKey("RuleTypeId", "BusinessAspectId");

                    b.HasIndex("BusinessAspectId");

                    b.ToTable("RuleTypeBusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeLocalization", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("RuleTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("RuleTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.Property<string>("ScheduleEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ScheduleEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduleStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ScheduleEntryId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ScheduleEntry", (string)null);
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryWorkers", b =>
                {
                    b.Property<string>("ScheduleEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ScheduleEntryId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ScheduleEntryWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShiftAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftDuration")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftStartHour")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.HasIndex("EntityId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreak", b =>
                {
                    b.Property<string>("ShiftBreakId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IncludedInShift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeFlexible")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ShiftBreakDuration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftBreakStartTime")
                        .HasColumnType("time");

                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShiftBreakId");

                    b.HasIndex("ShiftBreakTypeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.Property<int>("ShiftBreakTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftBreakTemplateId"));

                    b.Property<bool>("IncludedInShift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeFlexible")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ShiftBreakDuration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftBreakStartTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftBreakTemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateClicks")
                        .HasColumnType("int");

                    b.HasKey("ShiftBreakTemplateId");

                    b.HasIndex("ShiftBreakTypeId");

                    b.ToTable("ShiftBreakTemplates");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakType", b =>
                {
                    b.Property<int>("ShiftBreakTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftBreakTypeId"));

                    b.Property<string>("ShiftBreakTypeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftBreakTypeId");

                    b.ToTable("ShiftBreakTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTypeLocalization", b =>
                {
                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("ShiftBreakTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftBreakTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("ShiftBreakTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplate", b =>
                {
                    b.Property<int>("ShiftTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftTemplateId"));

                    b.Property<string>("ShiftAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftDuration")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftStartHour")
                        .HasColumnType("time");

                    b.Property<int>("TemplateClicks")
                        .HasColumnType("int");

                    b.HasKey("ShiftTemplateId");

                    b.ToTable("ShiftTemplates");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplateBreaks", b =>
                {
                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftBreakTemplateId")
                        .HasColumnType("int");

                    b.HasKey("ShiftTemplateId", "ShiftBreakTemplateId");

                    b.HasIndex("ShiftBreakTemplateId");

                    b.ToTable("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("HexBGColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexFontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("SkillDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.HasIndex("GenderId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.AbsenceType", "AbsenceType")
                        .WithMany("AbsenceTypeLocalizations")
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("AbsenceTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("BaseEntityRules")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRuleSpecification", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BaseEntityRule", "BaseEntityRule")
                        .WithMany("BaseEntityRuleSpecifications")
                        .HasForeignKey("BaseEntityRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseEntityRule");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspectLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BusinessAspect", "BusinessAspect")
                        .WithMany("BusinessAspectLocalizations")
                        .HasForeignKey("BusinessAspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("BusinessAspectLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAspect");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("Entities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityRules")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("EntityRules")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRuleSpecification", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityRule", "EntityRule")
                        .WithMany("EntityRuleSpecifications")
                        .HasForeignKey("EntityRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityRule");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("SkillId");

                    b.HasOne("ShiftSchedularEntity.Entities.Worker", "Worker")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerAbsence", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.AbsenceType", "AbsenceType")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Worker", "Worker")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Entity");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerInvitation", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerInvitations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Worker", "Worker")
                        .WithMany("EntityWorkerInvitations")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Entity");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeBusinessAspect", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BusinessAspect", "BusinessAspect")
                        .WithMany("RuleTypeBusinessAspects")
                        .HasForeignKey("BusinessAspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("RuleTypeBusinessAspects")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAspect");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("RuleTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("RuleTypeLocalizations")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryWorkers", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany("ScheduleEntryWorkers")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Worker", "Worker")
                        .WithMany("ScheduleEntryWorkers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityShifts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreak", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreaks")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("ShiftBreaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreakTemplates")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("ShiftBreakTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreakTypeLocalizations")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplateBreaks", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakTemplate", "ShiftBreakTemplate")
                        .WithMany("ShiftTemplateBreaks")
                        .HasForeignKey("ShiftBreakTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany("ShiftTemplateBreaks")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftBreakTemplate");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("Workers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceType", b =>
                {
                    b.Navigation("AbsenceTypeLocalizations");

                    b.Navigation("EntityWorkerAbsences");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.Navigation("BaseEntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspect", b =>
                {
                    b.Navigation("BusinessAspectLocalizations");

                    b.Navigation("RuleTypeBusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Navigation("EntityRules");

                    b.Navigation("EntityShifts");

                    b.Navigation("EntityWorkerAbsences");

                    b.Navigation("EntityWorkerInvitations");

                    b.Navigation("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.Navigation("EntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Navigation("GenderLocalizations");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Navigation("AbsenceTypeLocalizations");

                    b.Navigation("BusinessAspectLocalizations");

                    b.Navigation("EntityTypeLocalizations");

                    b.Navigation("GenderLocalizations");

                    b.Navigation("RuleTypeLocalizations");

                    b.Navigation("ShiftBreakTypeLocalizations");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleType", b =>
                {
                    b.Navigation("BaseEntityRules");

                    b.Navigation("EntityRules");

                    b.Navigation("RuleTypeBusinessAspects");

                    b.Navigation("RuleTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.Navigation("ScheduleEntryWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.Navigation("ScheduleEntries");

                    b.Navigation("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.Navigation("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakType", b =>
                {
                    b.Navigation("ShiftBreakTemplates");

                    b.Navigation("ShiftBreakTypeLocalizations");

                    b.Navigation("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplate", b =>
                {
                    b.Navigation("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Navigation("EntityWorkers");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.Navigation("EntityWorkerAbsences");

                    b.Navigation("EntityWorkerInvitations");

                    b.Navigation("EntityWorkers");

                    b.Navigation("ScheduleEntryWorkers");
                });
#pragma warning restore 612, 618
        }
    }
}
