// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSchedularDAL.Data;

#nullable disable

namespace ShiftSchedularDAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240412090229_SkillBGColorColumn")]
    partial class SkillBGColorColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityTypeId"));

                    b.Property<string>("EntityTypeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("ActiveWorkerStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateSchedules")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.HasKey("EntityId", "WorkerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("WorkerId");

                    b.ToTable("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("GenderDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("GenderLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationId"));

                    b.Property<string>("LocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("HexBGColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("SkillDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.HasIndex("GenderId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("Entities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("SkillId");

                    b.HasOne("ShiftSchedularEntity.Entities.Worker", "Worker")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("Workers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Navigation("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Navigation("GenderLocalizations");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Navigation("EntityTypeLocalizations");

                    b.Navigation("GenderLocalizations");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Navigation("EntityWorkers");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.Navigation("EntityWorkers");
                });
#pragma warning restore 612, 618
        }
    }
}
