// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSchedularDAL.Data;

#nullable disable

namespace ShiftSchedularDAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250424093619_ScheduleEntryBotsAndSkillSpecs")]
    partial class ScheduleEntryBotsAndSkillSpecs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceType", b =>
                {
                    b.Property<int>("AbsenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbsenceTypeId"));

                    b.Property<string>("AbsenceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceTypeId");

                    b.ToTable("AbsenceTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceTypeLocalization", b =>
                {
                    b.Property<int>("AbsenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("AbsenceTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbsenceTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("AbsenceTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.Property<int>("BaseEntityRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaseEntityRuleId"));

                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.HasKey("BaseEntityRuleId");

                    b.HasIndex("RuleTypeId");

                    b.ToTable("BaseEntityRules");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRuleSpecification", b =>
                {
                    b.Property<int>("BaseEntityRuleId")
                        .HasColumnType("int");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpecValueBoolean")
                        .HasColumnType("bit");

                    b.Property<int>("SpecificationValue")
                        .HasColumnType("int");

                    b.HasKey("BaseEntityRuleId", "SpecificationId");

                    b.ToTable("BaseEntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspect", b =>
                {
                    b.Property<int>("BusinessAspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessAspectId"));

                    b.Property<string>("BusinessAspectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessAspectId");

                    b.ToTable("BusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspectLocalization", b =>
                {
                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessAspectDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessAspectId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("BusinessAspectLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("EntityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.Property<byte[]>("EntityRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("RuleTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.HasKey("EntityRuleId");

                    b.HasIndex("EntityId");

                    b.HasIndex("RuleTypeId");

                    b.ToTable("EntityRules");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRuleSpecification", b =>
                {
                    b.Property<byte[]>("EntityRuleId")
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<string>("AspectReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspectReferenceId2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId2")
                        .HasColumnType("int");

                    b.Property<float>("SpecificationValue")
                        .HasColumnType("real");

                    b.HasKey("EntityRuleId", "SpecificationId");

                    b.ToTable("EntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityShiftRotation", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeave")
                        .HasColumnType("bit");

                    b.Property<long>("LeaveDuration")
                        .HasColumnType("BIGINT");

                    b.Property<byte[]>("ShiftId")
                        .HasColumnType("BINARY(16)");

                    b.HasKey("EntityId", "OrderNo", "IsLeave");

                    b.ToTable("EntityShiftRotations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityTypeId"));

                    b.Property<string>("EntityTypeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("EntityTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBot", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("UserBotId")
                        .HasColumnType("BINARY(16)");

                    b.Property<bool>("ActiveWorkerStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfExit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PartOfRotation")
                        .HasColumnType("bit");

                    b.Property<bool>("WorksWeekDays")
                        .HasColumnType("bit");

                    b.Property<bool>("WorksWeekends")
                        .HasColumnType("bit");

                    b.HasKey("EntityId", "UserBotId");

                    b.HasIndex("UserBotId");

                    b.ToTable("EntityUserBots");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBotShiftAssigned", b =>
                {
                    b.Property<byte[]>("UserBotId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("ShiftId")
                        .HasColumnType("BINARY(16)");

                    b.HasKey("UserBotId", "EntityId", "ShiftId");

                    b.HasIndex("EntityId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EntityUserBotShiftAssigneds");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBotSkill", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("UserBotId")
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("EntityId", "UserBotId", "SkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserBotId");

                    b.ToTable("EntityUserBotSkills");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ActiveWorkerStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateSchedules")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateToExit")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("PartOfRotation")
                        .HasColumnType("bit");

                    b.Property<bool>("WorksWeekDays")
                        .HasColumnType("bit");

                    b.Property<bool>("WorksWeekends")
                        .HasColumnType("bit");

                    b.HasKey("EntityId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerAbsence", b =>
                {
                    b.Property<byte[]>("EntityWorkerAbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<bool>("AbsenceApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AbsenceDateDecision")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AbsenceDateDecisionOffset")
                        .HasColumnType("time");

                    b.Property<string>("AbsenceDecisionOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AbsenceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AbsenceStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AbsenceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("DateOffset")
                        .HasColumnType("time");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EntityWorkerAbsenceId");

                    b.HasIndex("AbsenceTypeId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("EntityId");

                    b.ToTable("WorkerEntityAbsences");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerInvitation", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InviteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PartOfRotation")
                        .HasColumnType("bit");

                    b.Property<string>("SkillsetIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WorksWeekDays")
                        .HasColumnType("bit");

                    b.Property<bool>("WorksWeekends")
                        .HasColumnType("bit");

                    b.HasKey("EntityId", "Email");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("EntityWorkerInvitations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerShiftAssigned", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("ShiftId")
                        .HasColumnType("BINARY(16)");

                    b.HasKey("ApplicationUserId", "EntityId", "ShiftId");

                    b.HasIndex("EntityId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EntityWorkerShiftAssigneds");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerSkill", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "EntityId", "SkillId");

                    b.HasIndex("EntityId");

                    b.HasIndex("SkillId");

                    b.ToTable("EntityWorkerSkills");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("GenderDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("GenderLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationId"));

                    b.Property<string>("LocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleType", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleTypeId"));

                    b.Property<bool>("IsSpecValuesBoolean")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleSpecification")
                        .HasColumnType("bit");

                    b.Property<string>("RuleTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleTypeId");

                    b.ToTable("RuleTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeBusinessAspect", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessAspectId")
                        .HasColumnType("int");

                    b.HasKey("RuleTypeId", "BusinessAspectId");

                    b.HasIndex("BusinessAspectId");

                    b.ToTable("RuleTypeBusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeLocalization", b =>
                {
                    b.Property<int>("RuleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("RuleTypeDescriptionDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("RuleTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.Property<byte[]>("ScheduleEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("ScheduleEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduleStartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ShiftId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("ScheduleEntryId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ScheduleEntry", (string)null);
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryBots", b =>
                {
                    b.Property<byte[]>("ScheduleEntryId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("UserBotId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("SpecificSkillAssignments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleEntryId", "UserBotId");

                    b.HasIndex("UserBotId");

                    b.ToTable("ScheduleEntryBots");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryWorkers", b =>
                {
                    b.Property<byte[]>("ScheduleEntryId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpecificSkillAssignments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleEntryId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ScheduleEntryWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.Property<byte[]>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("ShiftAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("ShiftDuration")
                        .HasColumnType("TIME");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ShiftStartHour")
                        .HasColumnType("TIME");

                    b.HasKey("ShiftId");

                    b.HasIndex("EntityId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreak", b =>
                {
                    b.Property<byte[]>("ShiftBreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<bool>("IncludedInShift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeFlexible")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ShiftBreakDuration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftBreakStartTime")
                        .HasColumnType("time");

                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ShiftId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("ShiftBreakId");

                    b.HasIndex("ShiftBreakTypeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.Property<int>("ShiftBreakTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftBreakTemplateId"));

                    b.Property<bool>("IncludedInShift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeFlexible")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ShiftBreakDuration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftBreakStartTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftBreakTemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateClicks")
                        .HasColumnType("int");

                    b.HasKey("ShiftBreakTemplateId");

                    b.HasIndex("ShiftBreakTypeId");

                    b.ToTable("ShiftBreakTemplates");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakType", b =>
                {
                    b.Property<int>("ShiftBreakTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftBreakTypeId"));

                    b.Property<string>("ShiftBreakTypeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftBreakTypeId");

                    b.ToTable("ShiftBreakTypes");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTypeLocalization", b =>
                {
                    b.Property<int>("ShiftBreakTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("ShiftBreakTypeDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShiftBreakTypeId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("ShiftBreakTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplate", b =>
                {
                    b.Property<int>("ShiftTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftTemplateId"));

                    b.Property<string>("ShiftAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftDuration")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ShiftStartHour")
                        .HasColumnType("time");

                    b.Property<int>("TemplateClicks")
                        .HasColumnType("int");

                    b.HasKey("ShiftTemplateId");

                    b.ToTable("ShiftTemplates");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplateBreaks", b =>
                {
                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftBreakTemplateId")
                        .HasColumnType("int");

                    b.HasKey("ShiftTemplateId", "ShiftBreakTemplateId");

                    b.HasIndex("ShiftBreakTemplateId");

                    b.ToTable("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("HexBGColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexFontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("SkillDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.UserBot", b =>
                {
                    b.Property<byte[]>("UserBotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserBotId");

                    b.ToTable("UserBots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.AbsenceType", "AbsenceType")
                        .WithMany("AbsenceTypeLocalizations")
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("AbsenceTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ApplicationUser", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("BaseEntityRules")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRuleSpecification", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BaseEntityRule", "BaseEntityRule")
                        .WithMany("BaseEntityRuleSpecifications")
                        .HasForeignKey("BaseEntityRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseEntityRule");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspectLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BusinessAspect", "BusinessAspect")
                        .WithMany("BusinessAspectLocalizations")
                        .HasForeignKey("BusinessAspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("BusinessAspectLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAspect");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("Entities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityRules")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("EntityRules")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRuleSpecification", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityRule", "EntityRule")
                        .WithMany("EntityRuleSpecifications")
                        .HasForeignKey("EntityRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityRule");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityShiftRotation", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityShiftRotations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.EntityType", "EntityType")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("EntityTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBot", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityUserBots")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.UserBot", "UserBot")
                        .WithMany("EntityUserBots")
                        .HasForeignKey("UserBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("UserBot");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBotShiftAssigned", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityUserBotShiftAssigneds")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("EntityUserBotShiftAssigned")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.UserBot", "UserBot")
                        .WithMany("EntityUserBotShiftAssigneds")
                        .HasForeignKey("UserBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Shift");

                    b.Navigation("UserBot");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityUserBotSkill", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityUserBotSkills")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("EntityUserBotSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.UserBot", "UserBot")
                        .WithMany("EntityUserBotSkills")
                        .HasForeignKey("UserBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Skill");

                    b.Navigation("UserBot");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkers")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerAbsence", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.AbsenceType", "AbsenceType")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerAbsences")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerInvitation", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("EntityWorkerInvitations")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerInvitations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerShiftAssigned", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("EntityWorkerShiftAssigneds")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerShiftAssigneds")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("EntityWorkerShiftAssigned")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Entity");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityWorkerSkill", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("EntityWorkerSkills")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityWorkerSkills")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("EntityWorkerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Entity");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeBusinessAspect", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.BusinessAspect", "BusinessAspect")
                        .WithMany("RuleTypeBusinessAspects")
                        .HasForeignKey("BusinessAspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("RuleTypeBusinessAspects")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAspect");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("RuleTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.RuleType", "RuleType")
                        .WithMany("RuleTypeLocalizations")
                        .HasForeignKey("RuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("RuleType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryBots", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany("ScheduleEntryBots")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.UserBot", "UserBot")
                        .WithMany("ScheduleEntryBots")
                        .HasForeignKey("UserBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("UserBot");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntryWorkers", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("ScheduleEntryWorkers")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ScheduleEntry", "ScheduleEntry")
                        .WithMany("ScheduleEntryWorkers")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("ScheduleEntry");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Entity", "Entity")
                        .WithMany("EntityShifts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreak", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreaks")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Shift", "Shift")
                        .WithMany("ShiftBreaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreakTemplates")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTypeLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("ShiftBreakTypeLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakType", "ShiftBreakType")
                        .WithMany("ShiftBreakTypeLocalizations")
                        .HasForeignKey("ShiftBreakTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("ShiftBreakType");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplateBreaks", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.ShiftBreakTemplate", "ShiftBreakTemplate")
                        .WithMany("ShiftTemplateBreaks")
                        .HasForeignKey("ShiftBreakTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany("ShiftTemplateBreaks")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftBreakTemplate");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.SkillLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Skill", "Skill")
                        .WithMany("SkillLocalizations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localization");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.AbsenceType", b =>
                {
                    b.Navigation("AbsenceTypeLocalizations");

                    b.Navigation("EntityWorkerAbsences");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ApplicationUser", b =>
                {
                    b.Navigation("EntityWorkerAbsences");

                    b.Navigation("EntityWorkerInvitations");

                    b.Navigation("EntityWorkerShiftAssigneds");

                    b.Navigation("EntityWorkerSkills");

                    b.Navigation("EntityWorkers");

                    b.Navigation("ScheduleEntryWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BaseEntityRule", b =>
                {
                    b.Navigation("BaseEntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.BusinessAspect", b =>
                {
                    b.Navigation("BusinessAspectLocalizations");

                    b.Navigation("RuleTypeBusinessAspects");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Entity", b =>
                {
                    b.Navigation("EntityRules");

                    b.Navigation("EntityShiftRotations");

                    b.Navigation("EntityShifts");

                    b.Navigation("EntityUserBotShiftAssigneds");

                    b.Navigation("EntityUserBotSkills");

                    b.Navigation("EntityUserBots");

                    b.Navigation("EntityWorkerAbsences");

                    b.Navigation("EntityWorkerInvitations");

                    b.Navigation("EntityWorkerShiftAssigneds");

                    b.Navigation("EntityWorkerSkills");

                    b.Navigation("EntityWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityRule", b =>
                {
                    b.Navigation("EntityRuleSpecifications");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.EntityType", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("EntityTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("GenderLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Navigation("AbsenceTypeLocalizations");

                    b.Navigation("BusinessAspectLocalizations");

                    b.Navigation("EntityTypeLocalizations");

                    b.Navigation("GenderLocalizations");

                    b.Navigation("RuleTypeLocalizations");

                    b.Navigation("ShiftBreakTypeLocalizations");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.RuleType", b =>
                {
                    b.Navigation("BaseEntityRules");

                    b.Navigation("EntityRules");

                    b.Navigation("RuleTypeBusinessAspects");

                    b.Navigation("RuleTypeLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ScheduleEntry", b =>
                {
                    b.Navigation("ScheduleEntryBots");

                    b.Navigation("ScheduleEntryWorkers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Shift", b =>
                {
                    b.Navigation("EntityUserBotShiftAssigned");

                    b.Navigation("EntityWorkerShiftAssigned");

                    b.Navigation("ScheduleEntries");

                    b.Navigation("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakTemplate", b =>
                {
                    b.Navigation("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftBreakType", b =>
                {
                    b.Navigation("ShiftBreakTemplates");

                    b.Navigation("ShiftBreakTypeLocalizations");

                    b.Navigation("ShiftBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.ShiftTemplate", b =>
                {
                    b.Navigation("ShiftTemplateBreaks");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Skill", b =>
                {
                    b.Navigation("EntityUserBotSkills");

                    b.Navigation("EntityWorkerSkills");

                    b.Navigation("SkillLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.UserBot", b =>
                {
                    b.Navigation("EntityUserBotShiftAssigneds");

                    b.Navigation("EntityUserBotSkills");

                    b.Navigation("EntityUserBots");

                    b.Navigation("ScheduleEntryBots");
                });
#pragma warning restore 612, 618
        }
    }
}
