// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSchedularDAL.Data;

#nullable disable

namespace ShiftSchedularDAL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<string>("GenderDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId", "LocalizationId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("GenderLocalizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationId"));

                    b.Property<string>("LocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.Property<long>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.HasIndex("GenderId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.GenderLocalization", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSchedularEntity.Entities.Localization", "Localization")
                        .WithMany("GenderLocalizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Worker", b =>
                {
                    b.HasOne("ShiftSchedularEntity.Entities.Gender", "Gender")
                        .WithMany("Workers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Gender", b =>
                {
                    b.Navigation("GenderLocalizations");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ShiftSchedularEntity.Entities.Localization", b =>
                {
                    b.Navigation("GenderLocalizations");
                });
#pragma warning restore 612, 618
        }
    }
}
