//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.MemberManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityWorkerRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityWorkerRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.MemberManagement.EntityWorkerRelatedMessages", typeof(EntityWorkerRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member is already part of this work entity..
        /// </summary>
        public static string AddNewMemberAlreadyInEntity {
            get {
                return ResourceManager.GetString("AddNewMemberAlreadyInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New member name cannot be empty..
        /// </summary>
        public static string AddNewMemberBotNameEmpty {
            get {
                return ResourceManager.GetString("AddNewMemberBotNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New member was added successfuly..
        /// </summary>
        public static string AddNewMemberBotSuccessful {
            get {
                return ResourceManager.GetString("AddNewMemberBotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to associate member to the entity. .
        /// </summary>
        public static string AddNewMemberDestinationEntityEmpty {
            get {
                return ResourceManager.GetString("AddNewMemberDestinationEntityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New member cannot be invited without an email..
        /// </summary>
        public static string AddNewMemberEmailEmpty {
            get {
                return ResourceManager.GetString("AddNewMemberEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New member email is not in a valid format..
        /// </summary>
        public static string AddNewMemberEmailInvalid {
            get {
                return ResourceManager.GetString("AddNewMemberEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member invitation sent successfuly..
        /// </summary>
        public static string AddNewMemberInvitationSuccessful {
            get {
                return ResourceManager.GetString("AddNewMemberInvitationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while associating new member to entity. If this error persists, please contact support..
        /// </summary>
        public static string AddNewMemberNoDestinationEntityFound {
            get {
                return ResourceManager.GetString("AddNewMemberNoDestinationEntityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to add the new member. Please try again later..
        /// </summary>
        public static string AddNewMemberUnexpectedError {
            get {
                return ResourceManager.GetString("AddNewMemberUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member information was updated successfuly..
        /// </summary>
        public static string UpdateMemberSuccess {
            get {
                return ResourceManager.GetString("UpdateMemberSuccess", resourceCulture);
            }
        }
    }
}
