//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.AbsenceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AbsenceRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbsenceRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.AbsenceManagement.AbsenceRelatedMessages", typeof(AbsenceRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence identifier is required to perform this operation..
        /// </summary>
        public static string AbsenceIdIsNull {
            get {
                return ResourceManager.GetString("AbsenceIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string AbsenceNotFound {
            get {
                return ResourceManager.GetString("AbsenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was added successfuly..
        /// </summary>
        public static string AddEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("AddEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new absence. Please try again later..
        /// </summary>
        public static string AddEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("AddEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was deleted successfuly..
        /// </summary>
        public static string DeleteEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while deleting the absence. Please try again later..
        /// </summary>
        public static string DeleteEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was updated successfuly..
        /// </summary>
        public static string UpdateEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while updating the absence. Please try again later..
        /// </summary>
        public static string UpdateEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("UpdateEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
    }
}
