//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.AbsenceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AbsenceRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbsenceRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.AbsenceManagement.AbsenceRelatedMessages", typeof(AbsenceRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected dates are in an invalid format..
        /// </summary>
        public static string AbsenceDatesInvalidInterval {
            get {
                return ResourceManager.GetString("AbsenceDatesInvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence decision was submitted successfuly..
        /// </summary>
        public static string AbsenceDecisionApprovalSubmitted {
            get {
                return ResourceManager.GetString("AbsenceDecisionApprovalSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision approver is not eligible for performing this action..
        /// </summary>
        public static string AbsenceDecisionApproverIsNotOwner {
            get {
                return ResourceManager.GetString("AbsenceDecisionApproverIsNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the approval decision is required..
        /// </summary>
        public static string AbsenceDecisionApproverIsNull {
            get {
                return ResourceManager.GetString("AbsenceDecisionApproverIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while submitting the decision for absence approval. Please try again later..
        /// </summary>
        public static string AbsenceDecisionUnexpectedError {
            get {
                return ResourceManager.GetString("AbsenceDecisionUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence must have an end date..
        /// </summary>
        public static string AbsenceEndDateEmpty {
            get {
                return ResourceManager.GetString("AbsenceEndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence identifier is required to perform this operation..
        /// </summary>
        public static string AbsenceIdIsNull {
            get {
                return ResourceManager.GetString("AbsenceIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string AbsenceNotFound {
            get {
                return ResourceManager.GetString("AbsenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence must have an start date..
        /// </summary>
        public static string AbsenceStartDateEmpty {
            get {
                return ResourceManager.GetString("AbsenceStartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence type identifier is required for this operation..
        /// </summary>
        public static string AbsenceTypeIdRequired {
            get {
                return ResourceManager.GetString("AbsenceTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absence type is required..
        /// </summary>
        public static string AbsenceTypeIsInvalid {
            get {
                return ResourceManager.GetString("AbsenceTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No absence types found for the localization code.
        /// </summary>
        public static string AbsenceTypesNotFoundByLocal {
            get {
                return ResourceManager.GetString("AbsenceTypesNotFoundByLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was added successfuly..
        /// </summary>
        public static string AddEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("AddEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new absence. Please try again later..
        /// </summary>
        public static string AddEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("AddEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was deleted successfuly..
        /// </summary>
        public static string DeleteEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while deleting the absence. Please try again later..
        /// </summary>
        public static string DeleteEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the entity is required..
        /// </summary>
        public static string EntityIdIsEmpty {
            get {
                return ResourceManager.GetString("EntityIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity was found to be associated with the absence. If this error persists, please contact support..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Type value is required..
        /// </summary>
        public static string NewAbsenceTypeEmpty {
            get {
                return ResourceManager.GetString("NewAbsenceTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating a new absence type..
        /// </summary>
        public static string NewAbsenceTypeError {
            get {
                return ResourceManager.GetString("NewAbsenceTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence was updated successfuly..
        /// </summary>
        public static string UpdateEntityWorkerAbsenceSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateEntityWorkerAbsenceSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while updating the absence. Please try again later..
        /// </summary>
        public static string UpdateEntityWorkerAbsenceUnexpectedError {
            get {
                return ResourceManager.GetString("UpdateEntityWorkerAbsenceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the worker is required..
        /// </summary>
        public static string WorkerIdIsEmpty {
            get {
                return ResourceManager.GetString("WorkerIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worker was found to be associated with the absence. If this error continues, please contact support..
        /// </summary>
        public static string WorkerNotFound {
            get {
                return ResourceManager.GetString("WorkerNotFound", resourceCulture);
            }
        }
    }
}
