//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.ShiftManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.ShiftManagement.ShiftRelatedMessages", typeof(ShiftRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation added successfuly..
        /// </summary>
        public static string AddedToRotationSuccess {
            get {
                return ResourceManager.GetString("AddedToRotationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break type not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string AddNewShiftBreakBreakTypeNotFound {
            get {
                return ResourceManager.GetString("AddNewShiftBreakBreakTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break duration cannot be zero..
        /// </summary>
        public static string AddNewShiftBreakDurationIsNull {
            get {
                return ResourceManager.GetString("AddNewShiftBreakDurationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break destination cannot be empty..
        /// </summary>
        public static string AddNewShiftBreakEmptyShift {
            get {
                return ResourceManager.GetString("AddNewShiftBreakEmptyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break was added successfuly..
        /// </summary>
        public static string AddNewShiftBreakSuccessful {
            get {
                return ResourceManager.GetString("AddNewShiftBreakSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new shift break. Please try again later..
        /// </summary>
        public static string AddNewShiftBreakUnexpectedError {
            get {
                return ResourceManager.GetString("AddNewShiftBreakUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift duration cannot be zero..
        /// </summary>
        public static string AddNewShiftDurationIsNull {
            get {
                return ResourceManager.GetString("AddNewShiftDurationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift name cannot be empty..
        /// </summary>
        public static string AddNewShiftNameEmpty {
            get {
                return ResourceManager.GetString("AddNewShiftNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New shift was added successfuly..
        /// </summary>
        public static string AddNewShiftSuccessful {
            get {
                return ResourceManager.GetString("AddNewShiftSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while adding a new shift. Please try again later..
        /// </summary>
        public static string AddNewShiftUnexpectedError {
            get {
                return ResourceManager.GetString("AddNewShiftUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break identifier cannot be empty..
        /// </summary>
        public static string DeleteShiftBreakIdIsNull {
            get {
                return ResourceManager.GetString("DeleteShiftBreakIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while finding related shift breaks to this shift. If this continues, contact support to resolve this issue..
        /// </summary>
        public static string DeleteShiftBreaksNotFound {
            get {
                return ResourceManager.GetString("DeleteShiftBreaksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break was removed successfuly..
        /// </summary>
        public static string DeleteShiftBreakSuccessful {
            get {
                return ResourceManager.GetString("DeleteShiftBreakSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while deleting the shift break. Please try again later..
        /// </summary>
        public static string DeleteShiftBreakUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteShiftBreakUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the shift with existing future schedule entries associated to it..
        /// </summary>
        public static string DeleteShiftExistingScheduleEntries {
            get {
                return ResourceManager.GetString("DeleteShiftExistingScheduleEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while deleting the shift. Please try again later..
        /// </summary>
        public static string DeleteShiftUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteShiftUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while associating the destination entity to this shift operation. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave duration cannot be zero..
        /// </summary>
        public static string LeaveDurationIsZero {
            get {
                return ResourceManager.GetString("LeaveDurationIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L/NA.
        /// </summary>
        public static string LeaveNAAlias {
            get {
                return ResourceManager.GetString("LeaveNAAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave / NA.
        /// </summary>
        public static string LeaveNAPlaceholder {
            get {
                return ResourceManager.GetString("LeaveNAPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity identifier is required to perform this operation..
        /// </summary>
        public static string ShiftEntityIdIsNull {
            get {
                return ResourceManager.GetString("ShiftEntityIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift identifier is required to perform this operation..
        /// </summary>
        public static string ShiftIdIsNull {
            get {
                return ResourceManager.GetString("ShiftIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string ShiftNotFound {
            get {
                return ResourceManager.GetString("ShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift was removed successfuly..
        /// </summary>
        public static string ShiftRemovedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftRemovedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order number..
        /// </summary>
        public static string ShiftRotationBadOrderNumber {
            get {
                return ResourceManager.GetString("ShiftRotationBadOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift rotation data is required..
        /// </summary>
        public static string ShiftRotationDataNull {
            get {
                return ResourceManager.GetString("ShiftRotationDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift rotation was deleted successfuly..
        /// </summary>
        public static string ShiftRotationDeletedSuccess {
            get {
                return ResourceManager.GetString("ShiftRotationDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift rotation data is required to perform this operation..
        /// </summary>
        public static string ShiftRotationIsNull {
            get {
                return ResourceManager.GetString("ShiftRotationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while finding the related shift rotation. If this error persists, please contact support..
        /// </summary>
        public static string ShiftRotationNotFound {
            get {
                return ResourceManager.GetString("ShiftRotationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift was updated successfuly..
        /// </summary>
        public static string ShiftUpdatedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftUpdatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while updating the shift break. Please try again later..
        /// </summary>
        public static string UpdateShfitBreakUnexpectedError {
            get {
                return ResourceManager.GetString("UpdateShfitBreakUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift break was updated successfuly..
        /// </summary>
        public static string UpdateShiftBreakSuccessfuly {
            get {
                return ResourceManager.GetString("UpdateShiftBreakSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while finding the related shift. If this continues, contact support to resolve this issue..
        /// </summary>
        public static string UpdateShiftNotFound {
            get {
                return ResourceManager.GetString("UpdateShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift rotation updated successfuly.
        /// </summary>
        public static string UpdateShiftRotationSucess {
            get {
                return ResourceManager.GetString("UpdateShiftRotationSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while updating the shift. Please try again later..
        /// </summary>
        public static string UpdateShiftUnexpectedError {
            get {
                return ResourceManager.GetString("UpdateShiftUnexpectedError", resourceCulture);
            }
        }
    }
}
