//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.ShiftManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftTemplateRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftTemplateRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.ShiftManagement.ShiftTemplateRelatedMessages", typeof(ShiftTemplateRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template added successfuly..
        /// </summary>
        public static string ShiftBreakTemplateAddSuccesful {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateAddSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template and its associated records have been removed..
        /// </summary>
        public static string ShiftBreakTemplateDeletedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateDeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template needs a name..
        /// </summary>
        public static string ShiftBreakTemplateEmptyName {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template is required for operation to be executed..
        /// </summary>
        public static string ShiftBreakTemplateIdentifierIsZero {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateIdentifierIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shift Break Template record was found. .
        /// </summary>
        public static string ShiftBreakTemplateNotFound {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template Count updated..
        /// </summary>
        public static string ShiftBreakTemplatePopUpdateSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftBreakTemplatePopUpdateSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Template updated successfuly..
        /// </summary>
        public static string ShiftBreakTemplateUpdatedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftBreakTemplateUpdatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Break Type is not properly assigned..
        /// </summary>
        public static string ShiftBreakTypeIdentifierIsZero {
            get {
                return ResourceManager.GetString("ShiftBreakTypeIdentifierIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration cannot be zero.
        /// </summary>
        public static string ShiftDurationIsNotZero {
            get {
                return ResourceManager.GetString("ShiftDurationIsNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template added successfuly..
        /// </summary>
        public static string ShiftTemplateAddSuccesful {
            get {
                return ResourceManager.GetString("ShiftTemplateAddSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template and its associated records have been removed..
        /// </summary>
        public static string ShiftTemplateDeletedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftTemplateDeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template needs a name..
        /// </summary>
        public static string ShiftTemplateEmptyName {
            get {
                return ResourceManager.GetString("ShiftTemplateEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template is required for operation to be executed..
        /// </summary>
        public static string ShiftTemplateIdentifierIsZero {
            get {
                return ResourceManager.GetString("ShiftTemplateIdentifierIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shift Template record was found..
        /// </summary>
        public static string ShiftTemplateNotFound {
            get {
                return ResourceManager.GetString("ShiftTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template Count updated..
        /// </summary>
        public static string ShiftTemplatePopUpdateSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftTemplatePopUpdateSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Template and its associated records have been updated..
        /// </summary>
        public static string ShiftTemplateUpdatedSuccessfuly {
            get {
                return ResourceManager.GetString("ShiftTemplateUpdatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while executing operations with the template. If this continues, please contact support..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
