//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkerRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkerRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.Home.WorkerRelatedMessages", typeof(WorkerRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Scheduler - Confirm Email.
        /// </summary>
        public static string ConfirmEmailEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmEmailEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Scheduler - Forgot Password.
        /// </summary>
        public static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the email exists, a password reset link has been sent to the inputted email..
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token/refresh token.
        /// </summary>
        public static string InvalidTokens {
            get {
                return ResourceManager.GetString("InvalidTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was reset successfuly..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens are required..
        /// </summary>
        public static string TokensAreEmpty {
            get {
                return ResourceManager.GetString("TokensAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string WorkerEmailEmptyError {
            get {
                return ResourceManager.GetString("WorkerEmailEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot exceed 255 characters.
        /// </summary>
        public static string WorkerEmailExceedsLengthError {
            get {
                return ResourceManager.GetString("WorkerEmailExceedsLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        public static string WorkerEmailInUseError {
            get {
                return ResourceManager.GetString("WorkerEmailInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured, please try again later..
        /// </summary>
        public static string WorkerExceptionError {
            get {
                return ResourceManager.GetString("WorkerExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected gender value is invalid.
        /// </summary>
        public static string WorkerGenderUnexpectedValueError {
            get {
                return ResourceManager.GetString("WorkerGenderUnexpectedValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker identifier is required..
        /// </summary>
        public static string WorkerIdentifierIsEmpty {
            get {
                return ResourceManager.GetString("WorkerIdentifierIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found or invalid..
        /// </summary>
        public static string WorkerLoginEmailNotFoundError {
            get {
                return ResourceManager.GetString("WorkerLoginEmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string WorkerLoginPasswordIncorrect {
            get {
                return ResourceManager.GetString("WorkerLoginPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 255 characters.
        /// </summary>
        public static string WorkerNameExceedsLengthError {
            get {
                return ResourceManager.GetString("WorkerNameExceedsLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string WorkerPasswordEmptyError {
            get {
                return ResourceManager.GetString("WorkerPasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in invalid format..
        /// </summary>
        public static string WorkerRegistrationEmailInvalidError {
            get {
                return ResourceManager.GetString("WorkerRegistrationEmailInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string WorkerRegistrationNameEmptyError {
            get {
                return ResourceManager.GetString("WorkerRegistrationNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string WorkerRegistrationPasswordEmptyError {
            get {
                return ResourceManager.GetString("WorkerRegistrationPasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot exceed 128 characters.
        /// </summary>
        public static string WorkerRegistrationPasswordExceedsLengthError {
            get {
                return ResourceManager.GetString("WorkerRegistrationPasswordExceedsLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration was successful..
        /// </summary>
        public static string WorkerRegistrationSuccess {
            get {
                return ResourceManager.GetString("WorkerRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was updated successfuly..
        /// </summary>
        public static string WorkerUpdateSuccess {
            get {
                return ResourceManager.GetString("WorkerUpdateSuccess", resourceCulture);
            }
        }
    }
}
