<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources\Dashboard\EntitiesRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntitiesRelatedMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\EntityRuleManagement\EntityRulesRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntityRulesRelatedMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Home\WorkerRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WorkerRelatedMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MemberManagement\EntityWorkerRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntityWorkerRelatedMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ShiftManagement\ShiftRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShiftRelatedMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ShiftManagement\ShiftTemplateRelatedMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShiftTemplateRelatedMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Dashboard\EntitiesRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EntitiesRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\EntityRuleManagement\EntityRulesRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EntityRulesRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Home\WorkerRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WorkerRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MemberManagement\EntityWorkerRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EntityWorkerRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ShiftManagement\ShiftRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ShiftRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ShiftManagement\ShiftTemplateRelatedMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ShiftTemplateRelatedMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
