<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources\Dashboard\Entities.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Entities.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Home\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Dashboard\Entities.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Entities.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Home\Home.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
