//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntitiesRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitiesRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.Dashboard.EntitiesRelatedMessages", typeof(EntitiesRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Entity was created succesfully..
        /// </summary>
        public static string CreateEntitySuccess {
            get {
                return ResourceManager.GetString("CreateEntitySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when creating an worker entity. Please try again later..
        /// </summary>
        public static string CreateEntityUnexpectedError {
            get {
                return ResourceManager.GetString("CreateEntityUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the worker creating this entity cannot be null or empty..
        /// </summary>
        public static string CreateEntityWorkerOwnerEmptyError {
            get {
                return ResourceManager.GetString("CreateEntityWorkerOwnerEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity identifier cannot be null or empty..
        /// </summary>
        public static string DeleteEntityNoIdentifierError {
            get {
                return ResourceManager.GetString("DeleteEntityNoIdentifierError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when deleting an worker entity. Please try again later..
        /// </summary>
        public static string DeleteEntityUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteEntityUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity was received to perform the desired operation. If this error persists, contact support to resolve this issue..
        /// </summary>
        public static string EntityIsNullError {
            get {
                return ResourceManager.GetString("EntityIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name cannot be null or empty..
        /// </summary>
        public static string EntityNameEmptyError {
            get {
                return ResourceManager.GetString("EntityNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type for this entity has an invalid value.  If this error persists, contact support to resolve this issue..
        /// </summary>
        public static string EntityTypeInvalidValueError {
            get {
                return ResourceManager.GetString("EntityTypeInvalidValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work entity was not found..
        /// </summary>
        public static string UpdateEntityNotFound {
            get {
                return ResourceManager.GetString("UpdateEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Entity was updated successfully..
        /// </summary>
        public static string UpdateEntitySuccess {
            get {
                return ResourceManager.GetString("UpdateEntitySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when updating an worker entity. Please try again later..
        /// </summary>
        public static string UpdateEntityUnexpectedError {
            get {
                return ResourceManager.GetString("UpdateEntityUnexpectedError", resourceCulture);
            }
        }
    }
}
