//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.ScheduleManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScheduleRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.ScheduleManagement.ScheduleRelatedMessages", typeof(ScheduleRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start date inserted..
        /// </summary>
        public static string AddNewScheduleEntryInvalidStartDateError {
            get {
                return ResourceManager.GetString("AddNewScheduleEntryInvalidStartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift identifier cannot be empty..
        /// </summary>
        public static string AddNewScheduleEntryShiftEmptyError {
            get {
                return ResourceManager.GetString("AddNewScheduleEntryShiftEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule entry was added successfuly..
        /// </summary>
        public static string AddNewScheduleEntrySuccess {
            get {
                return ResourceManager.GetString("AddNewScheduleEntrySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a new schedule entry. Please try again later..
        /// </summary>
        public static string AddNewScheduleEntryUnexpectedError {
            get {
                return ResourceManager.GetString("AddNewScheduleEntryUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule participant added successfuly..
        /// </summary>
        public static string AddScheduleParticipantSuccess {
            get {
                return ResourceManager.GetString("AddScheduleParticipantSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while adding a schedule participant. Please try again later..
        /// </summary>
        public static string AddScheduleParticipantUnexpectedError {
            get {
                return ResourceManager.GetString("AddScheduleParticipantUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date inputted for this operation..
        /// </summary>
        public static string DateInvalidError {
            get {
                return ResourceManager.GetString("DateInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule entry was removed successfuly..
        /// </summary>
        public static string DeleteScheduleEntrySuccess {
            get {
                return ResourceManager.GetString("DeleteScheduleEntrySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured while removing a schedule entry. Please try again later..
        /// </summary>
        public static string DeleteScheduleEntryUnexpectedError {
            get {
                return ResourceManager.GetString("DeleteScheduleEntryUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule(s) participation(s) removed successfuly..
        /// </summary>
        public static string EntryParticipationRemoved {
            get {
                return ResourceManager.GetString("EntryParticipationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be smaller than the Start date..
        /// </summary>
        public static string InvalidDateInputOrder {
            get {
                return ResourceManager.GetString("InvalidDateInputOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule entries were not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string ScheduleEntriesNotFound {
            get {
                return ResourceManager.GetString("ScheduleEntriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule entries were removed successfuly..
        /// </summary>
        public static string ScheduleEntriesRemovedSuccess {
            get {
                return ResourceManager.GetString("ScheduleEntriesRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule(s) entry(ies) updated successfuly..
        /// </summary>
        public static string ScheduleEntriesUpdatedSuccessfuly {
            get {
                return ResourceManager.GetString("ScheduleEntriesUpdatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A schedule entry already exists for this shift..
        /// </summary>
        public static string ScheduleEntryAlreadyExistsError {
            get {
                return ResourceManager.GetString("ScheduleEntryAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule entry not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string ScheduleEntryNotFound {
            get {
                return ResourceManager.GetString("ScheduleEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule identifier is required to perform this operation..
        /// </summary>
        public static string ScheduleIdIsNull {
            get {
                return ResourceManager.GetString("ScheduleIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift not found. If this persists, contact support to resolve this issue..
        /// </summary>
        public static string ShiftNotFound {
            get {
                return ResourceManager.GetString("ShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date cannot be greater that the end date..
        /// </summary>
        public static string StartDateGreaterThanEndDateError {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker identifier is required to perform this operation..
        /// </summary>
        public static string WorkerIdIsNull {
            get {
                return ResourceManager.GetString("WorkerIdIsNull", resourceCulture);
            }
        }
    }
}
