//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSchedularRL.Resources.ScheduleManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScheduleGeneratorRelatedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleGeneratorRelatedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSchedularRL.Resources.ScheduleManagement.ScheduleGeneratorRelatedMessages", typeof(ScheduleGeneratorRelatedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker has a scheduled absence of type {0}..
        /// </summary>
        public static string AbsenceObs {
            get {
                return ResourceManager.GetString("AbsenceObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform next rotation entry due to scheduling times..
        /// </summary>
        public static string CannotDoNextRotationObs {
            get {
                return ResourceManager.GetString("CannotDoNextRotationObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry excluded due to not matching the next rotation entry..
        /// </summary>
        public static string ExcludedForNotMatchingNextRotationObs {
            get {
                return ResourceManager.GetString("ExcludedForNotMatchingNextRotationObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign due to consecutive entries without rest for a non rotation worker..
        /// </summary>
        public static string MandatoryRestDaysObs {
            get {
                return ResourceManager.GetString("MandatoryRestDaysObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker has mandatory rotation leave from {0} until {1}..
        /// </summary>
        public static string MandatoryRotationLeaveObs {
            get {
                return ResourceManager.GetString("MandatoryRotationLeaveObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max daily hours exceeded for this worker..
        /// </summary>
        public static string MaxDailyHoursObs {
            get {
                return ResourceManager.GetString("MaxDailyHoursObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker can only be assigned for one shift a day..
        /// </summary>
        public static string OneShiftPerDayObs {
            get {
                return ResourceManager.GetString("OneShiftPerDayObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker is already assigned..
        /// </summary>
        public static string WorkerAssignedToThisEntry {
            get {
                return ResourceManager.GetString("WorkerAssignedToThisEntry", resourceCulture);
            }
        }
    }
}
